# Generated by Django 4.1.13 on 2024-03-23 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kafka_topics', models.CharField(blank=True, default='', max_length=1024)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_types', to='sitevisorapi.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitevisorapi.point')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sitevisorapi.project')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sitevisorapi.sensortype')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('color', models.IntegerField()),
                ('opacity', models.FloatField()),
                ('height', models.FloatField(default=3)),
                ('point1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_point1', to='sitevisorapi.point')),
                ('point2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_point2', to='sitevisorapi.point')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='sitevisorapi.project')),
            ],
        ),
    ]
