# Generated by Django 4.1.13 on 2024-03-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisorapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='sensortype',
            unique_together={('name', 'project')},
        ),
    ]
