# Generated by Django 4.1.13 on 2024-03-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisorapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kafka_topics',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
