# Generated by Django 4.1.13 on 2024-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisorapi', '0002_project_kafka_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='kafka_topics',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
