# Generated by Django 4.1.13 on 2024-03-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisorapi', '0003_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='sitevisorapi.project'),
            preserve_default=False,
        ),
    ]
