# Generated by Django 4.1.13 on 2024-03-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisorapi', '0004_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sitevisorapi.room'),
        ),
    ]
