# Generated by Django 5.0.1 on 2024-02-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('color', models.BigIntegerField()),
                ('opacity', models.FloatField()),
                ('point1_x', models.FloatField()),
                ('point1_y', models.FloatField()),
                ('point1_z', models.FloatField()),
                ('point2_x', models.FloatField()),
                ('point2_y', models.FloatField()),
                ('point2_z', models.FloatField()),
                ('height', models.FloatField(default=3)),
            ],
        ),
    ]
