# Generated by Django 5.0.1 on 2024-02-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitevisor', '0002_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
